import type { Recipe } from './types';

export const SEED_RECIPES: Recipe[] = [
  {
    id: 'seed_1',
    title: 'High-Protein Paneer Bhurji',
    coverImage: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600',
    description: 'Scrambled paneer with onion, tomato, and spices. Classic Indian breakfast, macros actually hit.',
    dietType: 'veg', mealType: 'breakfast', cookingMethod: 'stovetop',
    prepTimeMin: 15, servings: 2, allergens: ['dairy'],
    ingredients: [
      { name: 'Paneer', grams: 200, notes: 'crumbled' }, { name: 'Onion', grams: 80 },
      { name: 'Tomato', grams: 100 }, { name: 'Green chilli', grams: 10 },
      { name: 'Mustard oil', grams: 10 }, { name: 'Turmeric', grams: 2 }, { name: 'Cumin seeds', grams: 3 },
    ],
    steps: [
      'Heat oil in pan. Add cumin seeds, let them splutter.',
      'Add chopped onion, cook till translucent.',
      'Add tomatoes and green chilli. Cook till soft.',
      'Add crumbled paneer, turmeric, salt. Mix well.',
      'Cook 3–4 min on medium heat. Serve hot.',
    ],
    macrosPerServing: { calories: 310, proteinG: 22, carbsG: 8, fatG: 22 },
    microsPerServing: { ironMg: 0.8, calciumMg: 500, b12Mcg: 0.6, vitaminDIu: 14, zincMg: 1.4 },
    aiQualityScore: 8, aiQualityReason: '22g protein per serving exceeds the MPS threshold. Calcium-rich from paneer. Consider adding spinach for iron.',
    upvotes: 847, postedAt: new Date(Date.now() - 5 * 24 * 3600000).toISOString(), authorLabel: 'Priya S.',
  },
  {
    id: 'seed_2',
    title: 'Masala Omelette (3-Egg)',
    coverImage: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600',
    description: '3-egg masala omelette with minimal oil. Best post-workout breakfast fr.',
    dietType: 'eggetarian', mealType: 'breakfast', cookingMethod: 'stovetop',
    prepTimeMin: 8, servings: 1, allergens: ['eggs'],
    ingredients: [
      { name: 'Whole eggs', grams: 150, notes: '3 eggs' }, { name: 'Onion', grams: 40 },
      { name: 'Tomato', grams: 50 }, { name: 'Green chilli', grams: 5 },
      { name: 'Sunflower oil', grams: 5 }, { name: 'Coriander', grams: 10 },
    ],
    steps: [
      'Beat eggs with salt and pepper.',
      'Fine chop onion, tomato, chilli, coriander.',
      'Mix vegetables into egg mixture.',
      'Heat oil in pan on medium. Pour mixture.',
      'Cook 2 min, fold, cook 1 min more.',
    ],
    macrosPerServing: { calories: 258, proteinG: 21, carbsG: 7, fatG: 16 },
    microsPerServing: { ironMg: 1.9, calciumMg: 80, b12Mcg: 1.4, vitaminDIu: 132, zincMg: 1.7 },
    aiQualityScore: 9, aiQualityReason: 'Exceptional protein-to-calorie ratio. High B12 and Vit D from eggs. Under 10 min prep.',
    upvotes: 1203, postedAt: new Date(Date.now() - 2 * 24 * 3600000).toISOString(), authorLabel: 'Arjun K.',
  },
  {
    id: 'seed_3',
    title: 'Chicken Breast + Dal Rice Bowl',
    coverImage: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=600',
    description: 'The classic Indian gym meal. Boiled chicken, toor dal, rice. Boring? Yes. Effective? fr.',
    dietType: 'non_veg', mealType: 'lunch', cookingMethod: 'stovetop',
    prepTimeMin: 30, servings: 1, allergens: [],
    ingredients: [
      { name: 'Chicken breast', grams: 150 }, { name: 'Toor dal (cooked)', grams: 150 },
      { name: 'White rice (cooked)', grams: 150 }, { name: 'Mustard oil', grams: 5 },
      { name: 'Turmeric', grams: 2 }, { name: 'Coriander powder', grams: 3 },
    ],
    steps: [
      'Pressure cook chicken breast with turmeric and salt (3 whistles).',
      'Shred or cube the cooked chicken.',
      'Prepare toor dal with basic tadka (oil + mustard seeds + turmeric).',
      'Serve rice, dal, and chicken together. Drizzle oil tadka over rice.',
    ],
    macrosPerServing: { calories: 545, proteinG: 58, carbsG: 55, fatG: 10 },
    microsPerServing: { ironMg: 3.5, calciumMg: 75, b12Mcg: 0.4, vitaminDIu: 6, zincMg: 3 },
    aiQualityScore: 9, aiQualityReason: '58g protein in one meal is exceptional. The gold standard Indian gym meal.',
    upvotes: 2341, postedAt: new Date(Date.now() - 10 * 24 * 3600000).toISOString(), authorLabel: 'Vikram P.',
  },
  {
    id: 'seed_4',
    title: 'Soya Chunks Curry',
    coverImage: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600',
    description: 'Budget-king veg protein. 52g protein per 100g dry weight. Indian-style masala curry.',
    dietType: 'veg', mealType: 'lunch', cookingMethod: 'stovetop',
    prepTimeMin: 25, servings: 2, allergens: ['soy'],
    ingredients: [
      { name: 'Soya chunks (dry)', grams: 100 }, { name: 'Onion', grams: 120 },
      { name: 'Tomato', grams: 150 }, { name: 'Sunflower oil', grams: 15 },
      { name: 'Garam masala', grams: 5 }, { name: 'Ginger garlic paste', grams: 15 },
    ],
    steps: [
      'Soak soya chunks in hot water 15 min. Squeeze out water.',
      'Sauté onions in oil till golden.',
      'Add ginger garlic paste, cook 2 min.',
      'Add tomatoes, cook till oil separates.',
      'Add soya chunks and garam masala, cook 8 min.',
      'Serve with roti or rice.',
    ],
    macrosPerServing: { calories: 280, proteinG: 26, carbsG: 20, fatG: 10 },
    microsPerServing: { ironMg: 4.2, calciumMg: 95, b12Mcg: 0, vitaminDIu: 0, zincMg: 1.4 },
    aiQualityScore: 8, aiQualityReason: 'Excellent plant protein density. Zero B12 — pair with dairy for the day.',
    upvotes: 956, postedAt: new Date(Date.now() - 7 * 24 * 3600000).toISOString(), authorLabel: 'Kavya R.',
  },
  {
    id: 'seed_5',
    title: 'Whey + Oats Overnight Bowl',
    coverImage: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600',
    description: 'No cook, prep the night before. 40g protein before you leave the house.',
    dietType: 'veg', mealType: 'pre_workout', cookingMethod: 'no_cook',
    prepTimeMin: 5, servings: 1, allergens: ['dairy', 'gluten'],
    ingredients: [
      { name: 'Rolled oats', grams: 80 }, { name: 'Whey protein', grams: 30, notes: '1 scoop' },
      { name: 'Full fat milk', grams: 250 }, { name: 'Banana', grams: 120 }, { name: 'Peanut butter', grams: 15 },
    ],
    steps: [
      'Mix oats, whey, and milk in a jar.',
      'Stir well so no lumps.',
      'Refrigerate overnight.',
      'Top with sliced banana and peanut butter in the morning.',
    ],
    macrosPerServing: { calories: 620, proteinG: 41, carbsG: 76, fatG: 15 },
    microsPerServing: { ironMg: 4.8, calciumMg: 400, b12Mcg: 1.2, vitaminDIu: 40, zincMg: 4.2 },
    aiQualityScore: 9, aiQualityReason: '41g protein with zero cooking time. Perfect pre-gym fuel.',
    upvotes: 1876, postedAt: new Date(Date.now() - 1 * 24 * 3600000).toISOString(), authorLabel: 'Siddharth M.',
  },
  {
    id: 'seed_6',
    title: 'Moong Dal Cheela',
    coverImage: 'https://images.unsplash.com/photo-1559181567-c3190bec5a4c?w=600',
    description: 'Soaked moong dal ground into batter, pan-fried thin. Indian protein pancake — ngl this slaps.',
    dietType: 'veg', mealType: 'breakfast', cookingMethod: 'stovetop',
    prepTimeMin: 20, servings: 2, allergens: [],
    ingredients: [
      { name: 'Moong dal (soaked overnight)', grams: 150 }, { name: 'Onion', grams: 60 },
      { name: 'Green chilli', grams: 8 }, { name: 'Ginger', grams: 10 },
      { name: 'Mustard oil', grams: 10 }, { name: 'Cumin seeds', grams: 3 },
    ],
    steps: [
      'Grind soaked moong dal with chilli and ginger into smooth batter.',
      'Add chopped onion, cumin seeds, salt.',
      'Heat oil in pan, pour ladle of batter, spread thin.',
      'Cook 2 min per side. Repeat.',
      'Serve with mint chutney.',
    ],
    macrosPerServing: { calories: 245, proteinG: 24, carbsG: 32, fatG: 7 },
    microsPerServing: { ironMg: 2.8, calciumMg: 55, b12Mcg: 0, vitaminDIu: 0, zincMg: 1.9 },
    aiQualityScore: 8, aiQualityReason: '24g protein per serving from whole legumes. Naturally gluten-free.',
    upvotes: 743, postedAt: new Date(Date.now() - 4 * 24 * 3600000).toISOString(), authorLabel: 'Ananya T.',
  },
  {
    id: 'seed_7',
    title: 'Rohu Fish Curry (Bengali Style)',
    coverImage: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600',
    description: 'Mustard-based Rohu curry. 17g protein per 100g, B12 through the roof.',
    dietType: 'non_veg', mealType: 'lunch', cookingMethod: 'stovetop',
    prepTimeMin: 35, servings: 2, allergens: ['fish'],
    ingredients: [
      { name: 'Rohu fish', grams: 300 }, { name: 'Mustard paste', grams: 30 },
      { name: 'Onion', grams: 80 }, { name: 'Tomato', grams: 100 },
      { name: 'Mustard oil', grams: 20 }, { name: 'Turmeric', grams: 3 },
    ],
    steps: [
      'Marinate fish with turmeric and salt 10 min.',
      'Shallow fry fish pieces in mustard oil. Set aside.',
      'In same pan, sauté onions golden. Add tomatoes.',
      'Add mustard paste, cook 3 min.',
      'Add fish back, simmer 10 min.',
    ],
    macrosPerServing: { calories: 320, proteinG: 28, carbsG: 6, fatG: 20 },
    microsPerServing: { ironMg: 1.6, calciumMg: 1010, b12Mcg: 3.1, vitaminDIu: 555, zincMg: 1.6 },
    aiQualityScore: 9, aiQualityReason: 'Exceptional B12 and Vit D levels. Best micronutrient density in the database.',
    upvotes: 612, postedAt: new Date(Date.now() - 8 * 24 * 3600000).toISOString(), authorLabel: 'Debashish B.',
  },
  {
    id: 'seed_8',
    title: 'Paneer Tikka (Air Fryer)',
    coverImage: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600',
    description: 'Classic tikka, no tandoor needed. Air fryer version hits 200°C and chars correctly.',
    dietType: 'veg', mealType: 'snack', cookingMethod: 'air_fryer',
    prepTimeMin: 25, servings: 2, allergens: ['dairy'],
    ingredients: [
      { name: 'Paneer', grams: 250 }, { name: 'Greek yogurt', grams: 100 },
      { name: 'Capsicum', grams: 80 }, { name: 'Onion', grams: 80 },
      { name: 'Tikka masala', grams: 20 }, { name: 'Sunflower oil', grams: 10 },
    ],
    steps: [
      'Cut paneer into 3cm cubes. Chop capsicum and onion same size.',
      'Mix yogurt, tikka masala, oil to make marinade.',
      'Coat paneer and veg. Rest 20 min.',
      'Air fry at 200°C for 12 min, turning once.',
      'Serve with green chutney.',
    ],
    macrosPerServing: { calories: 385, proteinG: 26, carbsG: 12, fatG: 27 },
    microsPerServing: { ironMg: 0.9, calciumMg: 620, b12Mcg: 0.8, vitaminDIu: 18, zincMg: 1.5 },
    aiQualityScore: 8, aiQualityReason: 'High protein with excellent calcium from paneer + yogurt combo.',
    upvotes: 1087, postedAt: new Date(Date.now() - 3 * 24 * 3600000).toISOString(), authorLabel: 'Meera J.',
  },
  {
    id: 'seed_9',
    title: 'Greek Yogurt Chaat',
    coverImage: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600',
    description: 'No cooking, 5 minutes, 30g protein. Post-workout snack or dahi-based side.',
    dietType: 'veg', mealType: 'snack', cookingMethod: 'no_cook',
    prepTimeMin: 5, servings: 1, allergens: ['dairy'],
    ingredients: [
      { name: 'Greek yogurt', grams: 200 }, { name: 'Cucumber', grams: 80 },
      { name: 'Tomato', grams: 60 }, { name: 'Red onion', grams: 30 },
      { name: 'Chaat masala', grams: 3 }, { name: 'Mint leaves', grams: 5 },
    ],
    steps: [
      'Dice cucumber, tomato, onion finely.',
      'Mix into Greek yogurt.',
      'Add chaat masala and salt.',
      'Garnish with mint.',
    ],
    macrosPerServing: { calories: 185, proteinG: 21, carbsG: 18, fatG: 2 },
    microsPerServing: { ironMg: 0.3, calciumMg: 235, b12Mcg: 1.6, vitaminDIu: 0, zincMg: 1.2 },
    aiQualityScore: 9, aiQualityReason: '21g protein in 5 minutes with zero oil. Underrated.',
    upvotes: 1490, postedAt: new Date(Date.now() - 6 * 24 * 3600000).toISOString(), authorLabel: 'Riya N.',
  },
  {
    id: 'seed_10',
    title: 'Egg White Bhurji',
    coverImage: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600',
    description: 'All protein, minimal fat. 6-egg-white bhurji. Aggressive cut food fr.',
    dietType: 'eggetarian', mealType: 'post_workout', cookingMethod: 'stovetop',
    prepTimeMin: 10, servings: 1, allergens: ['eggs'],
    ingredients: [
      { name: 'Egg whites', grams: 180, notes: '6 eggs separated' }, { name: 'Onion', grams: 50 },
      { name: 'Tomato', grams: 60 }, { name: 'Green chilli', grams: 5 },
      { name: 'Sunflower oil', grams: 5 }, { name: 'Cumin seeds', grams: 2 },
    ],
    steps: [
      'Separate egg whites into bowl. Beat lightly.',
      'Heat oil, add cumin seeds.',
      'Add onion, cook till soft.',
      'Add tomato and chilli, cook 3 min.',
      'Add egg whites, scramble on medium heat.',
    ],
    macrosPerServing: { calories: 220, proteinG: 22, carbsG: 10, fatG: 9 },
    microsPerServing: { ironMg: 0.3, calciumMg: 30, b12Mcg: 0.1, vitaminDIu: 0, zincMg: 0.3 },
    aiQualityScore: 7, aiQualityReason: 'High protein, very low fat. Good for aggressive cut phases.',
    upvotes: 534, postedAt: new Date(Date.now() - 9 * 24 * 3600000).toISOString(), authorLabel: 'Aditya V.',
  },
  {
    id: 'seed_11',
    title: 'Dal Makhani Lite',
    coverImage: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600',
    description: 'Dal makhani without the restaurant butter bomb. Same taste, 60% less fat.',
    dietType: 'veg', mealType: 'dinner', cookingMethod: 'stovetop',
    prepTimeMin: 40, servings: 3, allergens: ['dairy'],
    ingredients: [
      { name: 'Black urad dal', grams: 150 }, { name: 'Rajma', grams: 50 },
      { name: 'Tomato', grams: 200 }, { name: 'Onion', grams: 100 },
      { name: 'Greek yogurt', grams: 60, notes: 'instead of cream' },
      { name: 'Butter', grams: 10 }, { name: 'Ginger garlic paste', grams: 20 },
    ],
    steps: [
      'Soak urad dal and rajma overnight. Pressure cook 6 whistles.',
      'Sauté onions in butter till golden.',
      'Add ginger garlic paste, cook 3 min. Add tomatoes.',
      'Blend the tomato-onion base smooth.',
      'Add cooked dal. Simmer 20 min.',
      'Stir in yogurt off-flame. Do not boil after adding yogurt.',
    ],
    macrosPerServing: { calories: 295, proteinG: 22, carbsG: 44, fatG: 7 },
    microsPerServing: { ironMg: 5.8, calciumMg: 160, b12Mcg: 0.4, vitaminDIu: 4, zincMg: 2.6 },
    aiQualityScore: 8, aiQualityReason: 'Excellent iron and zinc. Classic Indian comfort food that actually works nutritionally.',
    upvotes: 2108, postedAt: new Date(Date.now() - 12 * 24 * 3600000).toISOString(), authorLabel: 'Shreya G.',
  },
  {
    id: 'seed_12',
    title: 'Tuna + Roti Roll',
    coverImage: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=600',
    description: "Canned tuna + mint chutney + roti. Under 10 min. 28g protein. ngl this is underrated.",
    dietType: 'non_veg', mealType: 'snack', cookingMethod: 'no_cook',
    prepTimeMin: 8, servings: 1, allergens: ['fish', 'gluten'],
    ingredients: [
      { name: 'Canned tuna in water', grams: 120 }, { name: 'Whole wheat roti', grams: 80, notes: '2 rotis' },
      { name: 'Mint chutney', grams: 20 }, { name: 'Onion', grams: 30 },
      { name: 'Lemon juice', grams: 10 }, { name: 'Black pepper', grams: 1 },
    ],
    steps: [
      'Drain tuna. Mix with diced onion, lemon juice, black pepper.',
      'Spread mint chutney on roti.',
      'Add tuna mixture, roll tightly.',
      'Serve immediately.',
    ],
    macrosPerServing: { calories: 370, proteinG: 28, carbsG: 42, fatG: 6 },
    microsPerServing: { ironMg: 1.5, calciumMg: 75, b12Mcg: 2.1, vitaminDIu: 0, zincMg: 1.4 },
    aiQualityScore: 8, aiQualityReason: '28g protein in under 10 minutes. Full B12 from tuna.',
    upvotes: 677, postedAt: new Date(Date.now() - 14 * 24 * 3600000).toISOString(), authorLabel: 'Karan B.',
  },
  {
    id: 'seed_13',
    title: 'Rajma Chawal (Protein Edition)',
    coverImage: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600',
    description: "Everyone's favourite, macros actually calculated. Complete amino profile.",
    dietType: 'veg', mealType: 'lunch', cookingMethod: 'stovetop',
    prepTimeMin: 45, servings: 2, allergens: [],
    ingredients: [
      { name: 'Rajma (cooked)', grams: 200 }, { name: 'White rice (cooked)', grams: 200 },
      { name: 'Onion', grams: 100 }, { name: 'Tomato', grams: 150 },
      { name: 'Mustard oil', grams: 15 }, { name: 'Garam masala', grams: 5 }, { name: 'Ginger garlic paste', grams: 20 },
    ],
    steps: [
      'Soak rajma overnight. Pressure cook 5 whistles.',
      'Sauté onions in oil till brown.',
      'Add ginger garlic paste, tomatoes, masalas.',
      'Add rajma with some cooking water. Simmer 15 min.',
      'Serve over rice.',
    ],
    macrosPerServing: { calories: 480, proteinG: 23, carbsG: 82, fatG: 8 },
    microsPerServing: { ironMg: 4.2, calciumMg: 88, b12Mcg: 0, vitaminDIu: 0, zincMg: 2.4 },
    aiQualityScore: 7, aiQualityReason: 'Rice + legume = complete protein profile. Zero B12 — add a glass of milk alongside.',
    upvotes: 3245, postedAt: new Date(Date.now() - 15 * 24 * 3600000).toISOString(), authorLabel: 'Pooja M.',
  },
  {
    id: 'seed_14',
    title: 'Chicken Tikka Bowl',
    coverImage: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600',
    description: 'Marinated chicken tikka over rice with raita. 45g protein, all macros accounted for.',
    dietType: 'non_veg', mealType: 'post_workout', cookingMethod: 'oven',
    prepTimeMin: 35, servings: 1, allergens: ['dairy'],
    ingredients: [
      { name: 'Chicken breast', grams: 200 }, { name: 'Greek yogurt', grams: 80 },
      { name: 'Tikka masala', grams: 15 }, { name: 'White rice (cooked)', grams: 150 },
      { name: 'Cucumber', grams: 60 }, { name: 'Sunflower oil', grams: 8 },
    ],
    steps: [
      'Marinate chicken in yogurt + tikka masala for 20 min.',
      'Bake at 220°C for 18 min, turning halfway.',
      'Make quick raita: remaining yogurt + cucumber + salt.',
      'Serve chicken over rice, raita alongside.',
    ],
    macrosPerServing: { calories: 565, proteinG: 45, carbsG: 52, fatG: 14 },
    microsPerServing: { ironMg: 1.3, calciumMg: 185, b12Mcg: 0.9, vitaminDIu: 14, zincMg: 2 },
    aiQualityScore: 9, aiQualityReason: '45g protein with complete post-workout carb replenishment. Oven method avoids excess oil.',
    upvotes: 1654, postedAt: new Date(Date.now() - 60 * 3600000).toISOString(), authorLabel: 'Nikhil S.',
  },
  {
    id: 'seed_15',
    title: 'Chana Masala (High Protein)',
    coverImage: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600',
    description: 'Chickpeas are underrated. Iron, zinc, and fibre all in one.',
    dietType: 'veg', mealType: 'lunch', cookingMethod: 'stovetop',
    prepTimeMin: 30, servings: 2, allergens: [],
    ingredients: [
      { name: 'Chickpeas (cooked)', grams: 250 }, { name: 'Onion', grams: 120 },
      { name: 'Tomato', grams: 150 }, { name: 'Mustard oil', grams: 15 },
      { name: 'Chole masala', grams: 10 }, { name: 'Ginger garlic paste', grams: 15 }, { name: 'Amchur powder', grams: 3 },
    ],
    steps: [
      'Pressure cook soaked chickpeas (4 whistles) or use canned.',
      'Brown onions in oil.',
      'Add ginger garlic paste and tomatoes. Cook till thick.',
      'Add chole masala, amchur, salt.',
      'Add chickpeas and water. Simmer 15 min.',
      'Garnish with raw onion rings and lemon.',
    ],
    macrosPerServing: { calories: 310, proteinG: 21, carbsG: 40, fatG: 9 },
    microsPerServing: { ironMg: 4.5, calciumMg: 110, b12Mcg: 0, vitaminDIu: 0, zincMg: 2.8 },
    aiQualityScore: 8, aiQualityReason: 'Excellent iron and zinc. Most underrated veg protein source in Indian cooking.',
    upvotes: 889, postedAt: new Date(Date.now() - 11 * 24 * 3600000).toISOString(), authorLabel: 'Tanvi K.',
  },
];
