#!/usr/bin/env node
/**
 * generate-graph.mjs — scans source files and outputs docs/CODEBASE_MAP.md
 * Run: npm run graph
 * Reads all .ts/.tsx in source dirs, extracts local imports + exports, builds a
 * compact architecture map that Claude can read in one shot instead of crawling files.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { join, relative, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const SOURCE_DIRS = ['app', 'components', 'src', 'lib', 'data', 'stores', 'context', 'hooks', 'types', 'constants'];

// Known project-local prefixes that appear without a leading ./
const LOCAL_PREFIXES = ['stores/', 'lib/', 'components/', 'hooks/', 'data/', 'context/', 'types/', 'src/', 'constants/', 'app/'];

function glob(dir, files = []) {
  if (!existsSync(dir)) return files;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory() && !['node_modules', '.git', 'android', 'assets', '.expo'].includes(entry.name)) {
      glob(full, files);
    } else if (entry.isFile() && /\.(ts|tsx)$/.test(entry.name) && !entry.name.endsWith('.d.ts')) {
      files.push(full);
    }
  }
  return files;
}

function resolveRelativeImport(importPath, fromFile) {
  if (!importPath.startsWith('.')) return importPath;
  const fromDir = dirname(fromFile);
  let resolved = join(fromDir, importPath);
  resolved = relative(ROOT, resolved).replace(/\\/g, '/');
  // strip extension if any
  resolved = resolved.replace(/\.(ts|tsx)$/, '');
  return resolved;
}

function extractLocalImports(content, filePath) {
  const rel = relative(ROOT, filePath).replace(/\\/g, '/');
  const imports = new Set();
  const importRegex = /from\s+['"]([^'"]+)['"]/g;
  let match;
  while ((match = importRegex.exec(content)) !== null) {
    const imp = match[1];
    if (imp.startsWith('@/')) {
      // tsconfig path alias: @/ → project root
      imports.add(imp.slice(2).replace(/\.(ts|tsx)$/, ''));
    } else if (imp.startsWith('.')) {
      const resolved = resolveRelativeImport(imp, filePath);
      if (!resolved.includes('node_modules')) imports.add(resolved);
    } else if (LOCAL_PREFIXES.some(p => imp.startsWith(p))) {
      imports.add(imp.replace(/\.(ts|tsx)$/, ''));
    }
  }
  // remove self-reference
  const selfKey = rel.replace(/\.(ts|tsx)$/, '');
  imports.delete(selfKey);
  return [...imports].sort();
}

function extractExports(content) {
  const exports = [];
  // default export with function/class/const name
  const defFn = content.match(/export\s+default\s+(?:function|class)\s+(\w+)/);
  if (defFn) exports.push(`${defFn[1]}*`);
  else {
    const defConst = content.match(/export\s+default\s+(\w+)\s*[;\n(]/);
    if (defConst) exports.push(`${defConst[1]}*`);
  }
  // named: function, const, class, type, interface, enum
  const named = [...content.matchAll(/^export\s+(?:const|function|class|type|interface|enum)\s+(\w+)/gm)];
  for (const m of named) {
    if (!exports.includes(`${m[1]}*`)) exports.push(m[1]);
  }
  return exports.slice(0, 6); // cap at 6 to stay compact
}

function fileRole(relPath) {
  if (relPath.startsWith('app/(tabs)/')) return 'tab-screen';
  if (relPath.startsWith('app/(onboarding)/')) return 'onboarding-screen';
  if (relPath.startsWith('app/')) return 'screen';
  if (relPath.startsWith('components/')) return 'component';
  if (relPath.startsWith('stores/')) return 'zustand-store';
  if (relPath.startsWith('lib/')) return 'util';
  if (relPath.startsWith('src/')) return 'engine';
  if (relPath.startsWith('data/')) return 'data';
  if (relPath.startsWith('hooks/')) return 'hook';
  if (relPath.startsWith('context/')) return 'context';
  if (relPath.startsWith('types/')) return 'types';
  if (relPath.startsWith('constants/')) return 'constants';
  return 'misc';
}

// ── gather all files ──────────────────────────────────────────────────────────
const allFiles = SOURCE_DIRS.flatMap(d => glob(join(ROOT, d)));
allFiles.sort();

const entries = allFiles.map(fp => {
  const content = readFileSync(fp, 'utf-8');
  const rel = relative(ROOT, fp).replace(/\\/g, '/');
  return {
    path: rel,
    role: fileRole(rel),
    imports: extractLocalImports(content, fp),
    exports: extractExports(content),
  };
});

// ── build markdown ────────────────────────────────────────────────────────────
const now = new Date().toISOString().slice(0, 10);

const lines = [
  `# Codebase Map`,
  `> Auto-generated by \`npm run graph\`. Do not edit manually. Run to refresh after adding/moving files.`,
  `> Last updated: ${now}`,
  ``,
  `## Directory Roles`,
  `| Dir | Role | Notes |`,
  `|-----|------|-------|`,
  `| \`app/\` | Expo Router screens | File-based routing |`,
  `| \`components/\` | Shared UI | Sub-dirs: \`workout/\`, \`recipes/\` |`,
  `| \`src/\` | Calculation engine | snake_case types — never import in UI |`,
  `| \`lib/\` | Utilities + bridges | Wraps src/ for UI consumption |`,
  `| \`stores/\` | Zustand state | MMKV-persisted |`,
  `| \`data/\` | Static data | foods, evidence, tracker-types |`,
  `| \`hooks/\` | Custom hooks | useColors() is THE theme hook |`,
  `| \`context/\` | React Context | Onboarding only — transient, not persisted |`,
  `| \`types/\` | TypeScript types | camelCase — UI types only |`,
  ``,
  `## Critical Type Boundary`,
  `- \`types/index.ts\` → \`UserProfile\` (camelCase, UI format) — **use everywhere in UI**`,
  `- \`src/types.ts\` → \`UserProfile\` (snake_case, engine format) — **never expose in UI**`,
  `- Bridge: \`stores/profile-store.ts\` calls \`computeResult()\` converting between the two`,
  ``,
  `## Storage Keys (never change — breaks existing user data)`,
  `- \`tapped_in_profile\` → profile-store`,
  `- \`tapped_in_tracker_logs\` → tracker-store`,
  `- \`tapped_in_onboarding_complete\` → onboarding gate`,
  ``,
  `## Navigation Flow`,
  `\`\`\``,
  `app/index.tsx → [hasOnboarding?] → /(tabs)/results OR /welcome`,
  `/welcome → /(onboarding)/step1 → step2 → step3 → step4(reveal) → /(tabs)/results`,
  `/log-meal → full-screen push (no tab bar)`,
  `\`\`\``,
  ``,
  `## File Dependency Graph`,
  `> Format: \`path\` [role] — imports: ... | exports: (* = default)`,
  ``,
];

// group by top-level dir
const groups = {};
for (const e of entries) {
  const top = e.path.split('/')[0];
  (groups[top] = groups[top] || []).push(e);
}

for (const [dir, files] of Object.entries(groups)) {
  lines.push(`### ${dir}/`);
  lines.push('');
  for (const f of files) {
    const name = f.path;
    const role = f.role;
    const imp = f.imports.length ? f.imports.map(i => `\`${i}\``).join(', ') : '—';
    const exp = f.exports.length ? f.exports.join(', ') : '—';
    lines.push(`**\`${name}\`** [${role}]`);
    lines.push(`- imports: ${imp}`);
    lines.push(`- exports: ${exp}`);
    lines.push('');
  }
}

// ── summary stats ─────────────────────────────────────────────────────────────
const roleCount = {};
for (const e of entries) roleCount[e.role] = (roleCount[e.role] || 0) + 1;
lines.push(`## Stats`);
lines.push(`Total source files: **${entries.length}**`);
lines.push('');
lines.push('| Role | Count |');
lines.push('|------|-------|');
for (const [r, c] of Object.entries(roleCount).sort((a, b) => b[1] - a[1])) {
  lines.push(`| ${r} | ${c} |`);
}

const output = lines.join('\n');
const outPath = join(ROOT, 'docs', 'CODEBASE_MAP.md');
writeFileSync(outPath, output, 'utf-8');
console.log(`✓ Wrote ${outPath} (${entries.length} files mapped)`);
